name: ecommerce_app
description: "A new ecommerce app project for learning purpose"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  bloc: ^8.1.1
  flutter_screenutil: ^5.9.3
  modal_progress_hud_nsn: ^0.5.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.12
  flutter_svg: ^2.0.9
  dropdown_button2: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat_Italic.ttf
          style: italic
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_Light.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 500
